### ISSUE TITLE
Would you like to see UMD version

### ISSUE THREAD

**Issue by nazar-pc** [coursera/scribe-plugin-table-command#3]
You're currently having CommonJS-only version, but would be nice to also support browser-centric AMD.
If this is something you're ready to accept - I'd like to send you a PR. What do you think?

**Comment by jnwng** [comment]
@nazar-pc while the source code itself is in CommonJS, the [webpack configuration provided](https://github.com/coursera/scribe-plugin-table-command/blob/master/webpack.config.min.js#L9) already outputs the library in the AMD format for consumption in the browser.

if you run `npm run build` in this folder, you should be able to get that output yourself.

**Comment by jnwng** [comment]
please re-open if you think this is still an issue!

**Comment by nazar-pc** [comment]
Yes, I still think this is issue, but can't reopen since maintainer (you) closed it, not me. CommonJS is for Node.js, but browsers load everything asynchronous and thus AMD is more suitable for browser environment (which this plugin seems to target).

Requiring (I have nothing against optional) build system to run such piece of code is ridiculous, it can support both AMD and globals without any issues out of the box.

So what I'm looking for is having working AMD support out of the box after installing package from NPM. If you don't want to make source AMD-compatible, you might just need to upload release builds to NPM instead of the sources (since you already have build command) and update `package.json` so that `main` will point to release file.

It is common to find `dist/project.js` and `dist/project.min.js` files in NPM package with `main: "dist/project.js"` in `package.json`.

As an example you can try `npm install jquery` and see the contents.

**Comment by jnwng** [comment]
understood - we don't actually use the NPM version of this module, so distributing the pre-built version was something that was overlooked. happy to add the release builds to the NPM distribution.

**Comment by nazar-pc** [comment]
Should I send a PR or you can tweak this yourself?

**Comment by jnwng** [comment]
if you have the bandwidth to make those adjustments (as it seems like you've done it before), i'm happy to accept a PR to add the AMD-wrapped version of module to the NPM distribution.
